# Travis CI settings

language: python

python:
  - '3.4'

env:
  matrix:
    - DB=sqlite DJANGO_VERSION=1.8.2

install:
  - pip install -r requirements.txt

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - python manage.py runserver &
  - sleep 3

script: paver