# Travis CI settings

language: python

python:
  - '3.4'

env:
  matrix:
    - DB=sqlite DJANGO_VERSION=1.8.2

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - sudo apt-get install phantomjs
  - npm install qunit-phantomjs-runner

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - python manage.py migrate
  - sleep 3
  - python manage.py runserver &
  - sleep 3

script:
  - paver
  - phantomjs node_modules/qunit-phantomjs-runner/runner.js lists/static/tests/tests.html
  - phantomjs node_modules/quint-phantomjs-runner/runner.js accounts/static/tests/tests.htnl